// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ehentai/model.proto at 6:1
package me.littlekey.earth.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Category extends Message<Category, Category.Builder> {
  public static final ProtoAdapter<Category> ADAPTER = new ProtoAdapter_Category();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NAME = "";

  public static final String DEFAULT_IMG = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String name;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String img;

  public Category(String name, String img) {
    this(name, img, ByteString.EMPTY);
  }

  public Category(String name, String img, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.name = name;
    this.img = img;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.name = name;
    builder.img = img;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Category)) return false;
    Category o = (Category) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(name, o.name)
        && Internal.equals(img, o.img);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (img != null ? img.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (name != null) builder.append(", name=").append(name);
    if (img != null) builder.append(", img=").append(img);
    return builder.replace(0, 2, "Category{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Category, Builder> {
    public String name;

    public String img;

    public Builder() {
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder img(String img) {
      this.img = img;
      return this;
    }

    @Override
    public Category build() {
      return new Category(name, img, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Category extends ProtoAdapter<Category> {
    ProtoAdapter_Category() {
      super(FieldEncoding.LENGTH_DELIMITED, Category.class);
    }

    @Override
    public int encodedSize(Category value) {
      return (value.name != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.name) : 0)
          + (value.img != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.img) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Category value) throws IOException {
      if (value.name != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name);
      if (value.img != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.img);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Category decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.img(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Category redact(Category value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
