// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: common.proto at 6:1
package me.littlekey.earth.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Cursor extends Message<Cursor, Cursor.Builder> {
  public static final ProtoAdapter<Cursor> ADAPTER = new ProtoAdapter_Cursor();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_CURSOR_ID = "";

  public static final Boolean DEFAULT_HAS_MORE = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String cursor_id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean has_more;

  public Cursor(String cursor_id, Boolean has_more) {
    this(cursor_id, has_more, ByteString.EMPTY);
  }

  public Cursor(String cursor_id, Boolean has_more, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.cursor_id = cursor_id;
    this.has_more = has_more;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.cursor_id = cursor_id;
    builder.has_more = has_more;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Cursor)) return false;
    Cursor o = (Cursor) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(cursor_id, o.cursor_id)
        && Internal.equals(has_more, o.has_more);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (cursor_id != null ? cursor_id.hashCode() : 0);
      result = result * 37 + (has_more != null ? has_more.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (cursor_id != null) builder.append(", cursor_id=").append(cursor_id);
    if (has_more != null) builder.append(", has_more=").append(has_more);
    return builder.replace(0, 2, "Cursor{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Cursor, Builder> {
    public String cursor_id;

    public Boolean has_more;

    public Builder() {
    }

    public Builder cursor_id(String cursor_id) {
      this.cursor_id = cursor_id;
      return this;
    }

    public Builder has_more(Boolean has_more) {
      this.has_more = has_more;
      return this;
    }

    @Override
    public Cursor build() {
      return new Cursor(cursor_id, has_more, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Cursor extends ProtoAdapter<Cursor> {
    ProtoAdapter_Cursor() {
      super(FieldEncoding.LENGTH_DELIMITED, Cursor.class);
    }

    @Override
    public int encodedSize(Cursor value) {
      return (value.cursor_id != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.cursor_id) : 0)
          + (value.has_more != null ? ProtoAdapter.BOOL.encodedSizeWithTag(2, value.has_more) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Cursor value) throws IOException {
      if (value.cursor_id != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.cursor_id);
      if (value.has_more != null) ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.has_more);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Cursor decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.cursor_id(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.has_more(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Cursor redact(Cursor value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
