// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: common.proto at 11:1
package me.littlekey.earth.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class NullMessage extends Message<NullMessage, NullMessage.Builder> {
  public static final ProtoAdapter<NullMessage> ADAPTER = new ProtoAdapter_NullMessage();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_SUCCESS = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean success;

  public NullMessage(Boolean success) {
    this(success, ByteString.EMPTY);
  }

  public NullMessage(Boolean success, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.success = success;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.success = success;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof NullMessage)) return false;
    NullMessage o = (NullMessage) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(success, o.success);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (success != null ? success.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (success != null) builder.append(", success=").append(success);
    return builder.replace(0, 2, "NullMessage{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<NullMessage, Builder> {
    public Boolean success;

    public Builder() {
    }

    public Builder success(Boolean success) {
      this.success = success;
      return this;
    }

    @Override
    public NullMessage build() {
      return new NullMessage(success, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_NullMessage extends ProtoAdapter<NullMessage> {
    ProtoAdapter_NullMessage() {
      super(FieldEncoding.LENGTH_DELIMITED, NullMessage.class);
    }

    @Override
    public int encodedSize(NullMessage value) {
      return (value.success != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.success) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, NullMessage value) throws IOException {
      if (value.success != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.success);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public NullMessage decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.success(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public NullMessage redact(NullMessage value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
