// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ehentai/home.proto at 6:1
package me.littlekey.earth.model.proto.ehentai;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class HomeListResponse extends Message<HomeListResponse, HomeListResponse.Builder> {
  public static final ProtoAdapter<HomeListResponse> ADAPTER = new ProtoAdapter_HomeListResponse();

  private static final long serialVersionUID = 0L;

  public HomeListResponse() {
    this(ByteString.EMPTY);
  }

  public HomeListResponse(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof HomeListResponse;
  }

  @Override
  public int hashCode() {
    return unknownFields().hashCode();
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "HomeListResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<HomeListResponse, Builder> {
    public Builder() {
    }

    @Override
    public HomeListResponse build() {
      return new HomeListResponse(buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_HomeListResponse extends ProtoAdapter<HomeListResponse> {
    ProtoAdapter_HomeListResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, HomeListResponse.class);
    }

    @Override
    public int encodedSize(HomeListResponse value) {
      return value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, HomeListResponse value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public HomeListResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public HomeListResponse redact(HomeListResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
